services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CI=true
    working_dir: /app
    command: npm run test

  playwright-ui:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "9323:9323"
    environment:
      - CI=false
    working_dir: /app
    command: npm run test:ui -- --host=0.0.0.0

  dev:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    working_dir: /app
    command: npm run dev